import { Request } from "@/types/request";

export const REQUESTS: Request[] = [
  {
    id: "1",
    service: "Fumigación de Cacao",
    client: "AgroExportadores S.A.",
    date: "2024-03-15",
    tons: 55,
    companyName: "AgroExportadores S.A.",
    companyLegalName: "AgroExportadores S.A. de C.V.",
    ruc: "12345678901",
    address: "Av. Principal 123, Zona Industrial, Ciudad Capital",
    phone: "+593 987 654 321",
    legalRep: "Juan Pérez Rodríguez",
    plantContact: "Ana Gómez López (Planta)",
    consignee: "Importadora Global Ltd.",
    lots: [
      {
        id: "ABC001",
        fumigationDate: "2023-10-15 08:00",
        destinationPort: "Puerto de Rotterdam",
        tons: 25,
        grade: "Grado A Premium",
        sacks: 500,
      },
      {
        id: "XYZ789",
        fumigationDate: "2023-10-18 14:30",
        destinationPort: "Puerto de Hamburgo",
        tons: 30,
        grade: "Grado B Estándar",
        sacks: 600,
      },
    ],
  },
  {
    id: "#12346",
    service: "Fumigación de Café",
    client: "Café del Valle",
    date: "2024-04-10",
    tons: 40,
    companyName: "Café del Valle S.A.",
    companyLegalName: "Café del Valle S.A. de C.V.",
    ruc: "23456789012",
    address: "Calle 45, Zona Cafetera, Ciudad Sierra",
    phone: "+593 912 345 678",
    legalRep: "María Fernanda Ruiz",
    plantContact: "Carlos Méndez (Planta)",
    consignee: "Distribuidora Europa S.L.",
    lots: [
      {
        id: "CAF100",
        fumigationDate: "2024-04-08 09:00",
        destinationPort: "Puerto de Valencia",
        tons: 40,
        grade: "Grado Exportación",
        sacks: 800,
      },
    ],
  },
  {
    id: "#12347",
    service: "Fumigación de Maíz",
    client: "Graneros Unidos",
    date: "2024-05-02",
    tons: 60,
    companyName: "Graneros Unidos S.A.",
    companyLegalName: "Graneros Unidos S.A. de C.V.",
    ruc: "34567890123",
    address: "Av. Maíz 200, Zona Agrícola, Ciudad Norte",
    phone: "+593 923 456 789",
    legalRep: "Luis Alberto Torres",
    plantContact: "Patricia Salazar (Planta)",
    consignee: "Importadora América Inc.",
    lots: [
      {
        id: "MAZ200",
        fumigationDate: "2024-05-01 07:30",
        destinationPort: "Puerto de Nueva York",
        tons: 60,
        grade: "Grado Superior",
        sacks: 1200,
      },
    ],
  },
  {
    id: "#12348",
    service: "Fumigación de Soya",
    client: "AgroSoya Export",
    date: "2024-06-12",
    tons: 35,
    companyName: "AgroSoya Export S.A.",
    companyLegalName: "AgroSoya Export S.A. de C.V.",
    ruc: "45678901234",
    address: "Ruta 7, Km 15, Zona Industrial, Ciudad Sur",
    phone: "+593 934 567 890",
    legalRep: "Gabriela Molina",
    plantContact: "Esteban Ríos (Planta)",
    consignee: "Comercializadora Asia Ltd.",
    lots: [
      {
        id: "SOY300",
        fumigationDate: "2024-06-10 10:00",
        destinationPort: "Puerto de Shanghái",
        tons: 35,
        grade: "Grado Exportación",
        sacks: 700,
      },
    ],
  },
];